sudo: required
services:
  - docker

before_install:
  - docker build -t inthebackofmymind/docker-react -f Dockerfile.dev .

script:
  - docker run inthebackofmymind/docker-react npm run test -- --coverage
